theme: jekyll-theme-leap-day
baseurl: /mau-predictor
show_downloads: true
title: Forecasting Monthly Active Users for Adobe Creative Cloud Products
description: View my capstone project for the M.Eng. degree at the University of California, Berkeley
